server:
  port: 8040
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dygstudio/xxxxxxxx/
          search-paths: config-repo
          username: xxxx
          password: xxxx