spring:
  application:
    name: microservice-hystrix-turbine
server:
  port: 8031
security:
  basic:
    enabled: false
turbine:
  aggregator:
    clusterConfig: default
  app-config: microservice-consumer-movie-feign-with-hystrix-stream,microservice-consumer-movie-ribbon-with-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
